## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file master.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_46 = Integer(46); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_51 = Integer(51); _sage_const_2 = Integer(2); _sage_const_53 = Integer(53); _sage_const_58 = Integer(58); _sage_const_1 = Integer(1); _sage_const_59 = Integer(59); _sage_const_63 = Integer(63); _sage_const_65 = Integer(65); _sage_const_67 = Integer(67); _sage_const_68 = Integer(68); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_69 = Integer(69); _sage_const_71 = Integer(71); _sage_const_73 = Integer(73); _sage_const_74 = Integer(74)## This file (master.sagetex.sage) was *autogenerated* from master.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('master', version='2021/10/16 v3.6', version_check=True)
try:
 _st_.current_tex_line = _sage_const_46 
 _st_.inline(_sage_const_0 , latex(number_of_partitions(_sage_const_8 )))
except:
 _st_.goboom(_sage_const_46 )
_st_.current_tex_line = _sage_const_51 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(exp(x) * sin(_sage_const_2 *x)).function(x)
except:
 _st_.goboom(_sage_const_53 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_58 
 _st_.inline(_sage_const_1 , latex(f(x)))
except:
 _st_.goboom(_sage_const_58 )
try:
 _st_.current_tex_line = _sage_const_59 
 _st_.inline(_sage_const_2 , latex(diff(f, x, _sage_const_2 )(x)))
except:
 _st_.goboom(_sage_const_59 )
try:
 _st_.current_tex_line = _sage_const_63 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f, -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_63 )
_st_.current_tex_line = _sage_const_65 
_st_.blockbegin()
try:
     __tmp__=var("x,y"); f = symbolic_expression(x*sin(y)).function(x,y); grad_f=f.gradient()
except:
 _st_.goboom(_sage_const_67 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_68 
 _st_.inline(_sage_const_3 , latex(f(x,y)))
except:
 _st_.goboom(_sage_const_68 )
try:
 _st_.current_tex_line = _sage_const_68 
 _st_.inline(_sage_const_4 , latex(grad_f(x,y)))
except:
 _st_.goboom(_sage_const_68 )
try:
 _st_.current_tex_line = _sage_const_69 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot_vector_field(grad_f, (x,-_sage_const_3 ,_sage_const_3 ), (y,_sage_const_0 ,_sage_const_3 )),frame=True, aspect_ratio=_sage_const_1 )
except:
 _st_.goboom(_sage_const_69 )
_st_.current_tex_line = _sage_const_71 
_st_.blockbegin()
try:
     __tmp__=var("x,y"); f = symbolic_expression(x*sin(y)+y*cos(x)).function(x,y)
except:
 _st_.goboom(_sage_const_73 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_74 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=plot3d(f,(x,-_sage_const_3 ,_sage_const_3 ),(y,-_sage_const_3 ,_sage_const_3 )))
except:
 _st_.goboom(_sage_const_74 )
_st_.endofdoc()

